### ISSUE TITLE
Add config option to specify container registry credentials for pulling bytecode images

### ISSUE THREAD

**Issue by astoycos** [redhat-et/bpfd#119]
Originates from https://github.com/redhat-et/bpfd/pull/102#discussion_r958350941

In https://github.com/redhat-et/bpfd/pull/102 we introduced the ability to extract bytecode from container images. 

These images are pulled from remote repositories and currently only public repositories are supported.  

We need to add a config option to `bpfd.toml` to authenticate against private image repositories 

something like 

```toml 
[ registry ]

[ registry.docker-io ]
username = foo
password = bar
```

and then nfer the registry from the image path and login if required.
