### ISSUE TITLE
Loading from `/etc/bpfd/programs.d`

### ISSUE THREAD

**Issue by dave-tucker** [redhat-et/bpfd#30]
We should support loading from `/etc/bpfd/programs.d/foo.toml`.
On start, the daemon would parse files from this directory and load them to the specified interface.
The configuration would look something like this:

```toml
[program]
interface ="eth0"
path = "/opt/bin/myapp/lib/myebpf.o"
section_name = "firewall"
program_type ="xdp"
priority = 50
```
